export const assignedClients = [
  {
    id: 1,
    name: "Karan Gupta",
    workout: "HIIT 5 Day",
    ptPlanName: "48 Sessions",
    sessionRemaining: "43",
    nextSessionDate: "10 December 2025",
  },
  {
    id: 2,
    name: "Arjun Verma",
    workout: "Yoga Flex",
    ptPlanName: "24 Sessions",
    sessionRemaining: "24",
    nextSessionDate: "29 January 2026",
  },
  {
    id: 3,
    name: "Ananya Reddy",
    workout: "Advanced Strength",
    ptPlanName: "48 Sessions",
    sessionRemaining: "39",
    nextSessionDate: "02 January 2026",
  },
  {
    id: 4,
    name: "Aditya Bansal",
    workout: "Functional Core",
    ptPlanName: "24 Sessions",
    sessionRemaining: "2",
    nextSessionDate: "21 January 2026",
  },
  {
    id: 5,
    name: "Karan Gupta",
    workout: "Functional Core",
    ptPlanName: "36 Sessions",
    sessionRemaining: "10",
    nextSessionDate: "25 January 2026",
  },
  {
    id: 6,
    name: "Priya Desai",
    workout: "Cardio Blast",
    ptPlanName: "24 Sessions",
    sessionRemaining: "9",
    nextSessionDate: "06 December 2025",
  },
  {
    id: 7,
    name: "Nikhil Sinha",
    workout: "Functional Core",
    ptPlanName: "36 Sessions",
    sessionRemaining: "15",
    nextSessionDate: "15 December 2025",
  },
  {
    id: 8,
    name: "Divya Iyer",
    workout: "Yoga Flex",
    ptPlanName: "24 Sessions",
    sessionRemaining: "15",
    nextSessionDate: "14 November 2025",
  },
  {
    id: 9,
    name: "Karan Gupta",
    workout: "HIIT 5 Day",
    ptPlanName: "36 Sessions",
    sessionRemaining: "33",
    nextSessionDate: "13 November 2025",
  },
  {
    id: 10,
    name: "Arjun Verma",
    workout: "Advanced Strength",
    ptPlanName: "12 Sessions",
    sessionRemaining: "10",
    nextSessionDate: "27 January 2026",
  },
  {
    id: 11,
    name: "Rahul Malhotra",
    workout: "Beginner’s 3 day",
    ptPlanName: "48 Sessions",
    sessionRemaining: "4",
    nextSessionDate: "15 November 2025",
  },
  {
    id: 12,
    name: "Priya Desai",
    workout: "HIIT 5 Day",
    ptPlanName: "24 Sessions",
    sessionRemaining: "8",
    nextSessionDate: "19 December 2025",
  },
  {
    id: 13,
    name: "Siddharth Rao",
    workout: "Beginner’s 3 day",
    ptPlanName: "48 Sessions",
    sessionRemaining: "26",
    nextSessionDate: "31 December 2025",
  },
  {
    id: 14,
    name: "Nikhil Sinha",
    workout: "HIIT 5 Day",
    ptPlanName: "24 Sessions",
    sessionRemaining: "3",
    nextSessionDate: "22 November 2025",
  },
  {
    id: 15,
    name: "Ananya Reddy",
    workout: "Beginner’s 3 day",
    ptPlanName: "12 Sessions",
    sessionRemaining: "0",
    nextSessionDate: "13 November 2025",
  },
  {
    id: 16,
    name: "Manish Joshi",
    workout: "Power Builder",
    ptPlanName: "48 Sessions",
    sessionRemaining: "22",
    nextSessionDate: "23 November 2025",
  },
  {
    id: 17,
    name: "Nikhil Sinha",
    workout: "Functional Core",
    ptPlanName: "48 Sessions",
    sessionRemaining: "37",
    nextSessionDate: "18 November 2025",
  },
  {
    id: 18,
    name: "Aarav Mehta",
    workout: "Beginner’s 3 day",
    ptPlanName: "36 Sessions",
    sessionRemaining: "10",
    nextSessionDate: "04 February 2026",
  },
  {
    id: 19,
    name: "Aditi Ghosh",
    workout: "Cardio Blast",
    ptPlanName: "24 Sessions",
    sessionRemaining: "2",
    nextSessionDate: "03 December 2025",
  },
  {
    id: 20,
    name: "Manish Joshi",
    workout: "Yoga Flex",
    ptPlanName: "12 Sessions",
    sessionRemaining: "6",
    nextSessionDate: "29 January 2026",
  },
  {
    id: 21,
    name: "Manish Joshi",
    workout: "Advanced Strength",
    ptPlanName: "12 Sessions",
    sessionRemaining: "7",
    nextSessionDate: "01 January 2026",
  },
  {
    id: 22,
    name: "Karan Gupta",
    workout: "Yoga Flex",
    ptPlanName: "12 Sessions",
    sessionRemaining: "9",
    nextSessionDate: "28 November 2025",
  },
  {
    id: 23,
    name: "Meera Bhattacharya",
    workout: "Advanced Strength",
    ptPlanName: "48 Sessions",
    sessionRemaining: "25",
    nextSessionDate: "05 January 2026",
  },
  {
    id: 24,
    name: "Nikhil Sinha",
    workout: "Cardio Blast",
    ptPlanName: "48 Sessions",
    sessionRemaining: "41",
    nextSessionDate: "08 January 2026",
  },
  {
    id: 25,
    name: "Aarav Mehta",
    workout: "Endurance Pro",
    ptPlanName: "36 Sessions",
    sessionRemaining: "0",
    nextSessionDate: "20 November 2025",
  },
  {
    id: 26,
    name: "Nikhil Sinha",
    workout: "Full Body Burn",
    ptPlanName: "12 Sessions",
    sessionRemaining: "6",
    nextSessionDate: "26 November 2025",
  },
  {
    id: 27,
    name: "Kavya Nair",
    workout: "Cardio Blast",
    ptPlanName: "48 Sessions",
    sessionRemaining: "11",
    nextSessionDate: "05 December 2025",
  },
  {
    id: 28,
    name: "Rahul Malhotra",
    workout: "Full Body Burn",
    ptPlanName: "36 Sessions",
    sessionRemaining: "8",
    nextSessionDate: "02 December 2025",
  },
  {
    id: 29,
    name: "Arjun Verma",
    workout: "Advanced Strength",
    ptPlanName: "12 Sessions",
    sessionRemaining: "11",
    nextSessionDate: "09 December 2025",
  },
  {
    id: 30,
    name: "Siddharth Rao",
    workout: "Beginner’s 3 day",
    ptPlanName: "12 Sessions",
    sessionRemaining: "3",
    nextSessionDate: "13 November 2025",
  },
  {
    id: 31,
    name: "Meera Bhattacharya",
    workout: "Beginner’s 3 day",
    ptPlanName: "24 Sessions",
    sessionRemaining: "8",
    nextSessionDate: "31 December 2025",
  },
  {
    id: 32,
    name: "Priya Desai",
    workout: "Full Body Burn",
    ptPlanName: "48 Sessions",
    sessionRemaining: "34",
    nextSessionDate: "26 January 2026",
  },
  {
    id: 33,
    name: "Rahul Malhotra",
    workout: "Yoga Flex",
    ptPlanName: "24 Sessions",
    sessionRemaining: "6",
    nextSessionDate: "18 January 2026",
  },
  {
    id: 34,
    name: "Sneha Pillai",
    workout: "Full Body Burn",
    ptPlanName: "48 Sessions",
    sessionRemaining: "14",
    nextSessionDate: "15 November 2025",
  },
  {
    id: 35,
    name: "Kavya Nair",
    workout: "Power Builder",
    ptPlanName: "48 Sessions",
    sessionRemaining: "43",
    nextSessionDate: "19 December 2025",
  },
  {
    id: 36,
    name: "Aditya Bansal",
    workout: "HIIT 5 Day",
    ptPlanName: "12 Sessions",
    sessionRemaining: "4",
    nextSessionDate: "31 January 2026",
  },
  {
    id: 37,
    name: "Kavya Nair",
    workout: "Full Body Burn",
    ptPlanName: "24 Sessions",
    sessionRemaining: "23",
    nextSessionDate: "08 January 2026",
  },
  {
    id: 38,
    name: "Ananya Reddy",
    workout: "HIIT 5 Day",
    ptPlanName: "12 Sessions",
    sessionRemaining: "9",
    nextSessionDate: "30 January 2026",
  },
  {
    id: 39,
    name: "Rahul Malhotra",
    workout: "Advanced Strength",
    ptPlanName: "36 Sessions",
    sessionRemaining: "34",
    nextSessionDate: "19 January 2026",
  },
  {
    id: 40,
    name: "Aarav Mehta",
    workout: "Full Body Burn",
    ptPlanName: "36 Sessions",
    sessionRemaining: "0",
    nextSessionDate: "28 November 2025",
  },
  {
    id: 41,
    name: "Manish Joshi",
    workout: "Yoga Flex",
    ptPlanName: "48 Sessions",
    sessionRemaining: "18",
    nextSessionDate: "01 December 2025",
  },
  {
    id: 42,
    name: "Isha Patel",
    workout: "Beginner’s 3 day",
    ptPlanName: "48 Sessions",
    sessionRemaining: "25",
    nextSessionDate: "27 December 2025",
  },
  {
    id: 43,
    name: "Sneha Pillai",
    workout: "Advanced Strength",
    ptPlanName: "36 Sessions",
    sessionRemaining: "30",
    nextSessionDate: "17 December 2025",
  },
  {
    id: 44,
    name: "Kavya Nair",
    workout: "Functional Core",
    ptPlanName: "36 Sessions",
    sessionRemaining: "27",
    nextSessionDate: "23 January 2026",
  },
  {
    id: 45,
    name: "Aarav Mehta",
    workout: "Advanced Strength",
    ptPlanName: "48 Sessions",
    sessionRemaining: "19",
    nextSessionDate: "25 December 2025",
  },
  {
    id: 46,
    name: "Arjun Verma",
    workout: "Endurance Pro",
    ptPlanName: "24 Sessions",
    sessionRemaining: "6",
    nextSessionDate: "31 January 2026",
  },
  {
    id: 47,
    name: "Kavya Nair",
    workout: "Functional Core",
    ptPlanName: "36 Sessions",
    sessionRemaining: "12",
    nextSessionDate: "14 November 2025",
  },
  {
    id: 48,
    name: "Aarav Mehta",
    workout: "Functional Core",
    ptPlanName: "12 Sessions",
    sessionRemaining: "6",
    nextSessionDate: "13 January 2026",
  },
  {
    id: 49,
    name: "Arjun Verma",
    workout: "Beginner’s 3 day",
    ptPlanName: "36 Sessions",
    sessionRemaining: "3",
    nextSessionDate: "14 December 2025",
  },
  {
    id: 50,
    name: "Manish Joshi",
    workout: "HIIT 5 Day",
    ptPlanName: "48 Sessions",
    sessionRemaining: "0",
    nextSessionDate: "19 January 2026",
  },
  {
    id: 51,
    name: "Sneha Pillai",
    workout: "Yoga Flex",
    ptPlanName: "36 Sessions",
    sessionRemaining: "23",
    nextSessionDate: "14 November 2025",
  },
  {
    id: 52,
    name: "Divya Iyer",
    workout: "Yoga Flex",
    ptPlanName: "36 Sessions",
    sessionRemaining: "21",
    nextSessionDate: "07 January 2026",
  },
  {
    id: 53,
    name: "Rohit Sharma",
    workout: "Endurance Pro",
    ptPlanName: "12 Sessions",
    sessionRemaining: "5",
    nextSessionDate: "11 January 2026",
  },
  {
    id: 54,
    name: "Rahul Malhotra",
    workout: "Beginner’s 3 day",
    ptPlanName: "12 Sessions",
    sessionRemaining: "10",
    nextSessionDate: "23 December 2025",
  },
  {
    id: 55,
    name: "Meera Bhattacharya",
    workout: "Yoga Flex",
    ptPlanName: "48 Sessions",
    sessionRemaining: "17",
    nextSessionDate: "06 December 2025",
  },
  {
    id: 56,
    name: "Siddharth Rao",
    workout: "Endurance Pro",
    ptPlanName: "48 Sessions",
    sessionRemaining: "28",
    nextSessionDate: "04 December 2025",
  },
  {
    id: 57,
    name: "Ananya Reddy",
    workout: "Advanced Strength",
    ptPlanName: "36 Sessions",
    sessionRemaining: "26",
    nextSessionDate: "30 November 2025",
  },
  {
    id: 58,
    name: "Ritika Jain",
    workout: "Beginner’s 3 day",
    ptPlanName: "24 Sessions",
    sessionRemaining: "15",
    nextSessionDate: "27 December 2025",
  },
  {
    id: 59,
    name: "Aditi Ghosh",
    workout: "Functional Core",
    ptPlanName: "36 Sessions",
    sessionRemaining: "35",
    nextSessionDate: "28 November 2025",
  },
  {
    id: 60,
    name: "Nikhil Sinha",
    workout: "HIIT 5 Day",
    ptPlanName: "12 Sessions",
    sessionRemaining: "1",
    nextSessionDate: "31 January 2026",
  },
  {
    id: 61,
    name: "Neha Kapoor",
    workout: "Functional Core",
    ptPlanName: "36 Sessions",
    sessionRemaining: "19",
    nextSessionDate: "29 December 2025",
  },
  {
    id: 62,
    name: "Siddharth Rao",
    workout: "Advanced Strength",
    ptPlanName: "24 Sessions",
    sessionRemaining: "2",
    nextSessionDate: "12 November 2025",
  },
  {
    id: 63,
    name: "Karan Gupta",
    workout: "Power Builder",
    ptPlanName: "24 Sessions",
    sessionRemaining: "9",
    nextSessionDate: "27 November 2025",
  },
  {
    id: 64,
    name: "Neha Kapoor",
    workout: "Advanced Strength",
    ptPlanName: "48 Sessions",
    sessionRemaining: "23",
    nextSessionDate: "14 November 2025",
  },
  {
    id: 65,
    name: "Kavya Nair",
    workout: "Advanced Strength",
    ptPlanName: "48 Sessions",
    sessionRemaining: "3",
    nextSessionDate: "04 February 2026",
  },
  {
    id: 66,
    name: "Karan Gupta",
    workout: "Functional Core",
    ptPlanName: "24 Sessions",
    sessionRemaining: "23",
    nextSessionDate: "28 December 2025",
  },
  {
    id: 67,
    name: "Rahul Malhotra",
    workout: "Full Body Burn",
    ptPlanName: "24 Sessions",
    sessionRemaining: "23",
    nextSessionDate: "29 December 2025",
  },
  {
    id: 68,
    name: "Ananya Reddy",
    workout: "Endurance Pro",
    ptPlanName: "48 Sessions",
    sessionRemaining: "25",
    nextSessionDate: "19 January 2026",
  },
  {
    id: 69,
    name: "Siddharth Rao",
    workout: "Power Builder",
    ptPlanName: "36 Sessions",
    sessionRemaining: "26",
    nextSessionDate: "31 January 2026",
  },
  {
    id: 70,
    name: "Priya Desai",
    workout: "HIIT 5 Day",
    ptPlanName: "36 Sessions",
    sessionRemaining: "15",
    nextSessionDate: "27 December 2025",
  },
];
